#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : requestsexceptions
Version  : 1.1.3
Release  : 8
URL      : http://tarballs.openstack.org/requestsexceptions/requestsexceptions-1.1.3.tar.gz
Source0  : http://tarballs.openstack.org/requestsexceptions/requestsexceptions-1.1.3.tar.gz
Summary  : Import exceptions from potentially bundled packages in requests.
Group    : Development/Tools
License  : Apache-2.0
Requires: requestsexceptions-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
requestsexceptions
==================
The python requests library bundles the urllib3 library, however, some
software distributions modify requests to remove the bundled library.
This makes some operations, such as supressing the "insecure platform
warning" messages that urllib emits difficult.  This is a simple
library to find the correct path to exceptions in the requests library
regardless of whether they are bundled.

%package python
Summary: python components for the requestsexceptions package.
Group: Default

%description python
python components for the requestsexceptions package.


%prep
%setup -q -n requestsexceptions-1.1.3

%build
export LANG=C
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
